"""empty message

Revision ID: 78b15b2f8129
Revises: 528293170c66
Create Date: 2020-12-02 14:57:53.626593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78b15b2f8129'
down_revision = '528293170c66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('permissions', sa.Integer(), nullable=True))
    op.drop_column('roles', 'permissions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('permissions', sa.INTEGER(), nullable=True))
    op.drop_column('roles', 'permissions')
    # ### end Alembic commands ###
